name: Build and Deploy InsightRFQ to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/insightrfq-app:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/insightrfq-app:${{ github.sha }}

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image # This job only runs if the build succeeds
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ThinkTank-RFP-ANALYSER' # Your Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Your existing publish profile
          images: '${{ secrets.ACR_LOGIN_SERVER }}/insightrfq-app:${{ github.sha }}'
